global using AutomationUtils.Utils;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using OpenQA.Selenium;
global using OpenQA.Selenium.Chrome;
global using OpenQA.Selenium.Edge;
global using OpenQA.Selenium.Firefox;
global using OpenQA.Selenium.Interactions;
global using OpenQA.Selenium.Opera;
global using OpenQA.Selenium.Support.UI;
global using Qwirkle.Domain.Entities;
global using Qwirkle.Domain.Enums;
global using Qwirkle.Domain.Ports;
global using Qwirkle.Domain.Services;
global using Qwirkle.Domain.ValueObjects;
global using Qwirkle.Infra.Repository;
global using Qwirkle.UltraBoardGames.Player;
global using Qwirkle.UltraBoardGames.Player.WebDriverFactory;
global using Qwirkle.UltraBoardGames.Player.WebElementExtensions;
global using Serilog;
global using SixLabors.ImageSharp;
global using SixLabors.ImageSharp.Processing;
global using System.Reflection;
global using WebDriverManager;
global using WebDriverManager.DriverConfigs.Impl;
global using Image = SixLabors.ImageSharp.Image;
global using Point = SixLabors.ImageSharp.Point;
global using Rectangle = SixLabors.ImageSharp.Rectangle;
global using Size = SixLabors.ImageSharp.Size;
global using RackPosition = System.Byte;
