// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_row", "trow5");
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_us", "tus5");
user_pref("app.normandy.startupExperimentPrefs.network.cookie.cookieBehavior", 5);
user_pref("app.normandy.startupExperimentPrefs.privacy.restrict3rdpartystorage.skip_list", "https://jalopnik.com,https://kinja.com;https://we.hamropatro.com,https://hamropatro.firebaseapp.com;https://stackblitz.com,*;*,https://www.blogger.com;*,https://scroll.com;https://www.messenger.com,https://www.facebook.com;https://knowyourmeme.com,https://trends.google.com");
user_pref("app.normandy.startupRolloutPrefs.fission.experiment.enrollmentStatus", 4);
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.sameSite.laxByDefault", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.sameSite.noneRequiresSecure", false);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "cf6c1a98-2fa8-4e90-8561-cdbbc23edb30");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.lastInstalledTaskVersion", 2);
user_pref("app.update.background.rolledout", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1644080039);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1644080041);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1644080036);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1644080070);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{8c6b0080-18d5-41cd-afb6-f8c96ada70a1}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1644080008);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 121);
user_pref("browser.newtabpage.activity-stream.impressionId", "{79777e70-e07d-42df-a7f1-832ca47b3655}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1644080044651");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1644081833651");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1644080039594");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1644101639594");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1644080019");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220126154723");
user_pref("browser.startup.homepage_override.mstone", "96.0.3");
user_pref("browser.startup.lastColdStartupCheck", 1644080014);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1644080024022");
user_pref("distribution.iniFile.exists.appversion", "96.0.3");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "bb8f045da7584b5482917f8a9fb0d94d");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 34);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220126154723");
user_pref("extensions.lastAppVersion", "96.0.3");
user_pref("extensions.lastPlatformVersion", "96.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"83d274fc-d242-42b6-8ac0-fd096d12de83\",\"formautofill@mozilla.org\":\"6d7f1c3a-ba50-441d-8753-ceb73fa49451\",\"pictureinpicture@mozilla.org\":\"af598bd0-d9cd-4672-b11f-948ea5ad4b87\",\"proxy-failover@mozilla.com\":\"0add9736-0436-4936-aeaf-aeab6d79d46c\",\"screenshots@mozilla.org\":\"2cfb01b4-6fb3-4873-84d3-dfd4a385040b\",\"webcompat-reporter@mozilla.org\":\"ccf7952d-c901-4302-b14e-eaef2c63e2c3\",\"webcompat@mozilla.org\":\"68f7d077-0677-4474-89b7-98769f4ac5fb\",\"default-theme@mozilla.org\":\"2902f22d-f5e6-42fb-a662-7bae85d4e096\",\"addons-search-detection@mozilla.com\":\"bd4cfd11-4b5c-4a33-a159-8b2cec494262\",\"google@search.mozilla.org\":\"75f3f48f-77f9-4094-90fa-63e59c20223c\",\"wikipedia@search.mozilla.org\":\"df044290-97ef-41c5-a8d7-1d347cd9a2b8\",\"bing@search.mozilla.org\":\"377410cf-71ce-4e51-b72e-da651deb1162\",\"ddg@search.mozilla.org\":\"dd4db560-a167-4f48-ba7a-5819cc86a446\",\"ebay@search.mozilla.org\":\"7280d28a-9dde-459b-af4b-4576f92f5e9c\",\"qwant@search.mozilla.org\":\"a2ed8625-fdd9-4170-a228-a04de680135d\",\"uBlock0@raymondhill.net\":\"11be37ae-ef89-434a-9ade-b5a3bf029063\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1644080024);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("fission.experiment.startupEnrollmentStatus", 4);
user_pref("gfx-shader-check.build-version", "20220126154723");
user_pref("gfx-shader-check.device-id", "0x128b");
user_pref("gfx-shader-check.driver-version", "27.21.14.6647");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x128b");
user_pref("sanity-test.driver-version", "27.21.14.6647");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20220126154723");
user_pref("security.sandbox.content.tempDirSuffix", "{d7302e94-b403-426e-917b-fe5fd18bacfe}");
user_pref("toolkit.startup.last_success", 1644080007);
user_pref("toolkit.telemetry.cachedClientID", "b77d5fc0-3c1c-4f6a-95ca-861206d2fe11");
user_pref("toolkit.telemetry.previousBuildID", "20220126154723");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
