global using Microsoft.Extensions.Logging;
global using Qwirkle.Domain.Entities;
global using Qwirkle.Domain.Enums;
global using Qwirkle.Domain.ExtensionMethods;
global using Qwirkle.Domain.Ports;
global using Qwirkle.Domain.ValueObjects;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Threading.Tasks;
global using RackPosition = System.Byte;
global using Abscissa = System.SByte;
global using Ordinate = System.SByte;
