// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qwirkle.Infra.Repository;

#nullable disable

namespace Qwirkle.Infra.Repository.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20220326125942_ChangeTileOnPlayerToTileOnRack")]
    partial class ChangeTileOnPlayerToTileOnRack
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "c306a26d-79d4-4ca9-a80a-346ef2477114",
                            Name = "Bot",
                            NormalizedName = "BOT"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "db3769b0-2153-495b-8ad6-dcda22c875a0",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "cf2becdc-1674-4a7a-8fa9-1086d8ab8be6",
                            Name = "Guest",
                            NormalizedName = "GUEST"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "92b50e60-7493-4f5b-92cc-6ef50f03ce02",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Qwirkle.Infra.Repository.Dao.GameDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GameOver")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastPlayDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Qwirkle.Infra.Repository.Dao.PlayerDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<byte>("GamePosition")
                        .HasColumnType("tinyint");

                    b.Property<bool>("GameTurn")
                        .HasColumnType("bit");

                    b.Property<byte>("LastTurnPoints")
                        .HasColumnType("tinyint");

                    b.Property<bool>("LastTurnSkipped")
                        .HasColumnType("bit");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Qwirkle.Infra.Repository.Dao.TileDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = 1,
                            Shape = 3
                        },
                        new
                        {
                            Id = 4,
                            Color = 1,
                            Shape = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = 1,
                            Shape = 5
                        },
                        new
                        {
                            Id = 6,
                            Color = 1,
                            Shape = 6
                        },
                        new
                        {
                            Id = 7,
                            Color = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 8,
                            Color = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 9,
                            Color = 2,
                            Shape = 3
                        },
                        new
                        {
                            Id = 10,
                            Color = 2,
                            Shape = 4
                        },
                        new
                        {
                            Id = 11,
                            Color = 2,
                            Shape = 5
                        },
                        new
                        {
                            Id = 12,
                            Color = 2,
                            Shape = 6
                        },
                        new
                        {
                            Id = 13,
                            Color = 3,
                            Shape = 1
                        },
                        new
                        {
                            Id = 14,
                            Color = 3,
                            Shape = 2
                        },
                        new
                        {
                            Id = 15,
                            Color = 3,
                            Shape = 3
                        },
                        new
                        {
                            Id = 16,
                            Color = 3,
                            Shape = 4
                        },
                        new
                        {
                            Id = 17,
                            Color = 3,
                            Shape = 5
                        },
                        new
                        {
                            Id = 18,
                            Color = 3,
                            Shape = 6
                        },
                        new
                        {
                            Id = 19,
                            Color = 4,
                            Shape = 1
                        },
                        new
                        {
                            Id = 20,
                            Color = 4,
                            Shape = 2
                        },
                        new
                        {
                            Id = 21,
                            Color = 4,
                            Shape = 3
                        },
                        new
                        {
                            Id = 22,
                            Color = 4,
                            Shape = 4
                        },
                        new
                        {
                            Id = 23,
                            Color = 4,
                            Shape = 5
                        },
                        new
                        {
                            Id = 24,
                            Color = 4,
                            Shape = 6
                        },
                        new
                        {
                            Id = 25,
                            Color = 5,
                            Shape = 1
                        },
                        new
                        {
                            Id = 26,
                            Color = 5,
                            Shape = 2
                        },
                        new
                        {
                            Id = 27,
                            Color = 5,
                            Shape = 3
                        },
                        new
                        {
                            Id = 28,
                            Color = 5,
                            Shape = 4
                        },
                        new
                        {
                            Id = 29,
                            Color = 5,
                            Shape = 5
                        },
                        new
                        {
                            Id = 30,
                            Color = 5,
                            Shape = 6
                        },
                        new
                        {
                            Id = 31,
                            Color = 6,
                            Shape = 1
                        },
                        new
                        {
                            Id = 32,
                            Color = 6,
                            Shape = 2
                        },
                        new
                        {
                            Id = 33,
                            Color = 6,
                            Shape = 3
                        },
                        new
                        {
                            Id = 34,
                            Color = 6,
                            Shape = 4
                        },
                        new
                        {
                            Id = 35,
                            Color = 6,
                            Shape = 5
                        },
                        new
                        {
                            Id = 36,
                            Color = 6,
                            Shape = 6
                        },
                        new
                        {
                            Id = 37,
                            Color = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 38,
                            Color = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 39,
                            Color = 1,
                            Shape = 3
                        },
                        new
                        {
                            Id = 40,
                            Color = 1,
                            Shape = 4
                        },
                        new
                        {
                            Id = 41,
                            Color = 1,
                            Shape = 5
                        },
                        new
                        {
                            Id = 42,
                            Color = 1,
                            Shape = 6
                        },
                        new
                        {
                            Id = 43,
                            Color = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 44,
                            Color = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 45,
                            Color = 2,
                            Shape = 3
                        },
                        new
                        {
                            Id = 46,
                            Color = 2,
                            Shape = 4
                        },
                        new
                        {
                            Id = 47,
                            Color = 2,
                            Shape = 5
                        },
                        new
                        {
                            Id = 48,
                            Color = 2,
                            Shape = 6
                        },
                        new
                        {
                            Id = 49,
                            Color = 3,
                            Shape = 1
                        },
                        new
                        {
                            Id = 50,
                            Color = 3,
                            Shape = 2
                        },
                        new
                        {
                            Id = 51,
                            Color = 3,
                            Shape = 3
                        },
                        new
                        {
                            Id = 52,
                            Color = 3,
                            Shape = 4
                        },
                        new
                        {
                            Id = 53,
                            Color = 3,
                            Shape = 5
                        },
                        new
                        {
                            Id = 54,
                            Color = 3,
                            Shape = 6
                        },
                        new
                        {
                            Id = 55,
                            Color = 4,
                            Shape = 1
                        },
                        new
                        {
                            Id = 56,
                            Color = 4,
                            Shape = 2
                        },
                        new
                        {
                            Id = 57,
                            Color = 4,
                            Shape = 3
                        },
                        new
                        {
                            Id = 58,
                            Color = 4,
                            Shape = 4
                        },
                        new
                        {
                            Id = 59,
                            Color = 4,
                            Shape = 5
                        },
                        new
                        {
                            Id = 60,
                            Color = 4,
                            Shape = 6
                        },
                        new
                        {
                            Id = 61,
                            Color = 5,
                            Shape = 1
                        },
                        new
                        {
                            Id = 62,
                            Color = 5,
                            Shape = 2
                        },
                        new
                        {
                            Id = 63,
                            Color = 5,
                            Shape = 3
                        },
                        new
                        {
                            Id = 64,
                            Color = 5,
                            Shape = 4
                        },
                        new
                        {
                            Id = 65,
                            Color = 5,
                            Shape = 5
                        },
                        new
                        {
                            Id = 66,
                            Color = 5,
                            Shape = 6
                        },
                        new
                        {
                            Id = 67,
                            Color = 6,
                            Shape = 1
                        },
                        new
                        {
                            Id = 68,
                            Color = 6,
                            Shape = 2
                        },
                        new
                        {
                            Id = 69,
                            Color = 6,
                            Shape = 3
                        },
                        new
                        {
                            Id = 70,
                            Color = 6,
                            Shape = 4
                        },
                        new
                        {
                            Id = 71,
                            Color = 6,
                            Shape = 5
                        },
                        new
                        {
                            Id = 72,
                            Color = 6,
                            Shape = 6
                        },
                        new
                        {
                            Id = 73,
                            Color = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 74,
                            Color = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 75,
                            Color = 1,
                            Shape = 3
                        },
                        new
                        {
                            Id = 76,
                            Color = 1,
                            Shape = 4
                        },
                        new
                        {
                            Id = 77,
                            Color = 1,
                            Shape = 5
                        },
                        new
                        {
                            Id = 78,
                            Color = 1,
                            Shape = 6
                        },
                        new
                        {
                            Id = 79,
                            Color = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 80,
                            Color = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 81,
                            Color = 2,
                            Shape = 3
                        },
                        new
                        {
                            Id = 82,
                            Color = 2,
                            Shape = 4
                        },
                        new
                        {
                            Id = 83,
                            Color = 2,
                            Shape = 5
                        },
                        new
                        {
                            Id = 84,
                            Color = 2,
                            Shape = 6
                        },
                        new
                        {
                            Id = 85,
                            Color = 3,
                            Shape = 1
                        },
                        new
                        {
                            Id = 86,
                            Color = 3,
                            Shape = 2
                        },
                        new
                        {
                            Id = 87,
                            Color = 3,
                            Shape = 3
                        },
                        new
                        {
                            Id = 88,
                            Color = 3,
                            Shape = 4
                        },
                        new
                        {
                            Id = 89,
                            Color = 3,
                            Shape = 5
                        },
                        new
                        {
                            Id = 90,
                            Color = 3,
                            Shape = 6
                        },
                        new
                        {
                            Id = 91,
                            Color = 4,
                            Shape = 1
                        },
                        new
                        {
                            Id = 92,
                            Color = 4,
                            Shape = 2
                        },
                        new
                        {
                            Id = 93,
                            Color = 4,
                            Shape = 3
                        },
                        new
                        {
                            Id = 94,
                            Color = 4,
                            Shape = 4
                        },
                        new
                        {
                            Id = 95,
                            Color = 4,
                            Shape = 5
                        },
                        new
                        {
                            Id = 96,
                            Color = 4,
                            Shape = 6
                        },
                        new
                        {
                            Id = 97,
                            Color = 5,
                            Shape = 1
                        },
                        new
                        {
                            Id = 98,
                            Color = 5,
                            Shape = 2
                        },
                        new
                        {
                            Id = 99,
                            Color = 5,
                            Shape = 3
                        },
                        new
                        {
                            Id = 100,
                            Color = 5,
                            Shape = 4
                        },
                        new
                        {
                            Id = 101,
                            Color = 5,
                            Shape = 5
                        },
                        new
                        {
                            Id = 102,
                            Color = 5,
                            Shape = 6
                        },
                        new
                        {
                            Id = 103,
                            Color = 6,
                            Shape = 1
                        },
                        new
                        {
                            Id = 104,
                            Color = 6,
                            Shape = 2
                        },
                        new
                        {
                            Id = 105,
                            Color = 6,
                            Shape = 3
                        },
                        new
                        {
                            Id = 106,
                            Color = 6,
                            Shape = 4
                        },
                        new
                        {
                            Id = 107,
                            Color = 6,
                            Shape = 5
                        },
                        new
                        {
                            Id = 108,
                            Color = 6,
                            Shape = 6
                        });
                });

            modelBuilder.Entity("Qwirkle.Infra.Repository.Dao.TileOnBagDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("TileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TileId");

                    b.ToTable("TileOnBag");
                });

            modelBuilder.Entity("Qwirkle.Infra.Repository.Dao.TileOnBoardDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<short>("PositionX")
                        .HasColumnType("smallint");

                    b.Property<short>("PositionY")
                        .HasColumnType("smallint");

                    b.Property<int>("TileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TileId");

                    b.ToTable("TileOnBoard");
                });

            modelBuilder.Entity("Qwirkle.Infra.Repository.Dao.TileOnRackDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<byte>("RackPosition")
                        .HasColumnType("tinyint");

                    b.Property<int>("TileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TileId");

                    b.ToTable("TileOnRack");
                });

            modelBuilder.Entity("Qwirkle.Infra.Repository.Dao.UserDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("GamesWon")
                        .HasColumnType("int");

                    b.Property<int>("Help")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Pseudo");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[Pseudo] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fd09d246-ca43-421e-83d3-d2b1ac47b612",
                            Email = "bot1@bot",
                            EmailConfirmed = false,
                            GamesPlayed = 0,
                            GamesWon = 0,
                            Help = 0,
                            LockoutEnabled = false,
                            NormalizedUserName = "BOT1",
                            PhoneNumberConfirmed = false,
                            Points = 0,
                            TwoFactorEnabled = false,
                            UserName = "bot1"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3b41685c-0daa-4fbb-8367-2bb87de9b565",
                            Email = "bot2@bot",
                            EmailConfirmed = false,
                            GamesPlayed = 0,
                            GamesWon = 0,
                            Help = 0,
                            LockoutEnabled = false,
                            NormalizedUserName = "BOT2",
                            PhoneNumberConfirmed = false,
                            Points = 0,
                            TwoFactorEnabled = false,
                            UserName = "bot2"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "31a66166-636d-4b4b-af37-661b61a6b57c",
                            Email = "bot3@bot",
                            EmailConfirmed = false,
                            GamesPlayed = 0,
                            GamesWon = 0,
                            Help = 0,
                            LockoutEnabled = false,
                            NormalizedUserName = "BOT3",
                            PhoneNumberConfirmed = false,
                            Points = 0,
                            TwoFactorEnabled = false,
                            UserName = "bot3"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39e95c89-708d-4fd2-8d41-16540dc743fd",
                            Email = "bot4@bot",
                            EmailConfirmed = false,
                            GamesPlayed = 0,
                            GamesWon = 0,
                            Help = 0,
                            LockoutEnabled = false,
                            NormalizedUserName = "BOT4",
                            PhoneNumberConfirmed = false,
                            Points = 0,
                            TwoFactorEnabled = false,
                            UserName = "bot4"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d5cd71b-808f-4cbf-9455-d3450d7ca0c8",
                            Email = "thomas@newtomsoft.fr",
                            EmailConfirmed = false,
                            FirstName = "Thomas",
                            GamesPlayed = 0,
                            GamesWon = 0,
                            Help = 0,
                            LastName = "Vuille",
                            LockoutEnabled = false,
                            NormalizedEmail = "THOMAS@NEWTOMSOFT.FR",
                            NormalizedUserName = "TOM",
                            PasswordHash = "AQAAAAEAACcQAAAAED29kKSVgjTdA6s6pXQ0a+7iy9MJ5Y1byxFl2MWZnX4WE6lw1SsR9FGeGypraM3G+g==",
                            PhoneNumberConfirmed = false,
                            Points = 0,
                            SecurityStamp = "1121E638D8EA4D9682289069B38C23E1",
                            TwoFactorEnabled = false,
                            UserName = "Tom"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b8526d6e-133c-4c48-a716-e6b7aea1500c",
                            Email = "jc@jc.fr",
                            EmailConfirmed = false,
                            FirstName = "Jean Charles",
                            GamesPlayed = 0,
                            GamesWon = 0,
                            Help = 0,
                            LastName = "Gouleau",
                            LockoutEnabled = false,
                            NormalizedEmail = "JC@JC.FR",
                            NormalizedUserName = "JC",
                            PasswordHash = "AQAAAAEAACcQAAAAEJOr0iSf9bL59UJqwWyCpcjdampHsvulqOZ/NTApuuwLJsc1Sf9xRquQWPIz2S8rUQ==",
                            PhoneNumberConfirmed = false,
                            Points = 0,
                            SecurityStamp = "1CCCC7143D8942F38039F8DD9793921F",
                            TwoFactorEnabled = false,
                            UserName = "JC"
                        });
                });

            modelBuilder.Entity("UserDaoUserDao", b =>
                {
                    b.Property<int>("BookmarkedById")
                        .HasColumnType("int");

                    b.Property<int>("BookmarkedOpponentsId")
                        .HasColumnType("int");

                    b.HasKey("BookmarkedById", "BookmarkedOpponentsId");

                    b.HasIndex("BookmarkedOpponentsId");

                    b.ToTable("UserDaoUserDao");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Qwirkle.Infra.Repository.Dao.UserDao", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Qwirkle.Infra.Repository.Dao.UserDao", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qwirkle.Infra.Repository.Dao.UserDao", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Qwirkle.Infra.Repository.Dao.UserDao", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qwirkle.Infra.Repository.Dao.PlayerDao", b =>
                {
                    b.HasOne("Qwirkle.Infra.Repository.Dao.GameDao", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qwirkle.Infra.Repository.Dao.UserDao", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Qwirkle.Infra.Repository.Dao.TileOnBagDao", b =>
                {
                    b.HasOne("Qwirkle.Infra.Repository.Dao.GameDao", "Game")
                        .WithMany("TilesOnBag")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qwirkle.Infra.Repository.Dao.TileDao", "Tile")
                        .WithMany()
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Tile");
                });

            modelBuilder.Entity("Qwirkle.Infra.Repository.Dao.TileOnBoardDao", b =>
                {
                    b.HasOne("Qwirkle.Infra.Repository.Dao.GameDao", "Game")
                        .WithMany("TilesOnBoard")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qwirkle.Infra.Repository.Dao.TileDao", "Tile")
                        .WithMany()
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Tile");
                });

            modelBuilder.Entity("Qwirkle.Infra.Repository.Dao.TileOnRackDao", b =>
                {
                    b.HasOne("Qwirkle.Infra.Repository.Dao.PlayerDao", "Player")
                        .WithMany("Tiles")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qwirkle.Infra.Repository.Dao.TileDao", "Tile")
                        .WithMany()
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tile");
                });

            modelBuilder.Entity("UserDaoUserDao", b =>
                {
                    b.HasOne("Qwirkle.Infra.Repository.Dao.UserDao", null)
                        .WithMany()
                        .HasForeignKey("BookmarkedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qwirkle.Infra.Repository.Dao.UserDao", null)
                        .WithMany()
                        .HasForeignKey("BookmarkedOpponentsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qwirkle.Infra.Repository.Dao.GameDao", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("TilesOnBag");

                    b.Navigation("TilesOnBoard");
                });

            modelBuilder.Entity("Qwirkle.Infra.Repository.Dao.PlayerDao", b =>
                {
                    b.Navigation("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
