global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Qwirkle.Domain.Entities;
global using Qwirkle.Domain.Enums;
global using Qwirkle.Domain.Ports;
global using Qwirkle.Domain.Services;
global using Qwirkle.Domain.ValueObjects;
global using Qwirkle.Infra.Repository.Dao;
global using Qwirkle.Infra.Repository.DaoExtensionMethods;
global using Qwirkle.Infra.Repository.DomainExtensionMethods;
global using System;
global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Linq;
global using System.Threading.Tasks;
global using RackPosition = System.Byte;
